version: "3.9"

services:
  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    environment:
      - ENV=production

  celery:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.prod
    command: pipenv run celery -A core worker --loglevel=info
    environment:
      - ENV=production

  celery-beat:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.prod
    command: pipenv run celery -A core beat --loglevel=info
    environment:
      - ENV=production

  flower:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.prod
    command: pipenv run celery -A core flower --port=5555
    environment:
      - ENV=production

  redis:
    image: redis:7
    ports:
      - "6379:6379"