version: "3.9"

services:
  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    env_file:
      - ../.env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  celery:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    env_file:
      - ../.env
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    env_file:
      - ../.env
    depends_on:
      - db
      - redis

  flower:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    env_file:
      - ../.env
    ports:
      - "5555:5555"
    depends_on:
      - redis

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DJANGO_DB_NAME}
      POSTGRES_USER: ${DJANGO_DB_USER}
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: